channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==2.2.3
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
